# Generated by Django 5.0.2 on 2024-03-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_alter_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songnote',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
