# Generated by Django 5.0.2 on 2024-02-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_rename_text_post_title_post_comment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/sheetmusic/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(upload_to='media/pdfs/'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='sheetmusic.sheetmusicimage'),
        ),
    ]
