# Generated by Django 5.0.2 on 2024-03-20 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0003_alter_songnote_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetmusic.post'),
        ),
    ]
