# Generated by Django 5.0.2 on 2024-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusicimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='sheetmusicimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
