# Generated by Django 5.0.2 on 2024-03-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0006_sheetmusicimage_name_alter_post_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusicimage',
            name='name',
            field=models.CharField(blank=True, default='namenotset', max_length=50),
            preserve_default=False,
        ),
    ]
