# Generated by Django 5.0.2 on 2024-03-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0008_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='+', to='sheetmusic.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='created_post', to='sheetmusic.post'),
        ),
    ]
