# Generated by Django 5.0.2 on 2024-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0009_userprofile_liked_posts_userprofile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_posts',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ManyToManyField(to='sheetmusic.comment')),
                ('post', models.ManyToManyField(to='sheetmusic.post')),
                ('user', models.ManyToManyField(to='sheetmusic.userprofile')),
            ],
        ),
    ]
