# Generated by Django 5.0.2 on 2024-03-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='songs',
            field=models.ManyToManyField(blank=True, to='sheetmusic.song'),
        ),
    ]
