# Generated by Django 5.0.2 on 2024-03-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_remove_userprofile_liked_posts_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
