# Generated by Django 5.0.2 on 2024-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_post_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='end_timestamp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_timestamp',
            field=models.FloatField(default=0),
        ),
    ]
