# Generated by Django 5.0.3 on 2024-03-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0012_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
