# Generated by Django 5.0.3 on 2024-03-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0013_remove_room_id_room_room_code_room_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
    ]
