# Generated by Django 5.0.2 on 2024-03-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0016_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheetmusic.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
