# Generated by Django 5.0.2 on 2024-03-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0017_post_poster_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='pdfs/')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='SheetMusicImage',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, to='sheetmusic.pdf'),
        ),
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(blank=True, to='sheetmusic.video'),
        ),
    ]
