# Generated by Django 5.0.2 on 2024-03-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0018_pdf_video_rename_sheetmusicimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='video',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
